name: Deploy API on Kamatera Server

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Adjust the version based on your application's requirements

    - name: Install Dependencies
      run: npm install  # or yarn install if you're using Yarn

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: herzliyaaa/library-upskill-api:latest
        context: .

    # - name: Deploy to Ubuntu server
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     key: ${{ secrets.PRIVATE_KEY }}
    #     port: 22
    #     script: |
    #       cd /opt/api/lib
    #       sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #       sudo docker pull herzliyaaa/library-upskill-api:latest
    #       sudo docker-compose up -d --build
